name: Sync

on:
  schedule:
    - cron:  '0 18 * * 4'
  workflow_dispatch:  
  
jobs:
  one:
    runs-on: ubuntu-latest
    env:
      INPUT_GITHUB_TOKEN: ${{ secrets.PAT }}
      INPUT_UPSTREAM_REPOSITORY: ${{ secrets.UR1 }}
      TARGET_REPOSITORY: ${{ secrets.TR1 }}
      INPUT_TARGET_BRANCH: ${{ secrets.BR1 }}
      INPUT_UPSTREAM_BRANCH: ${{ secrets.BR1 }}
    steps:
      - name: Sync
        run: |
          upstream_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${INPUT_UPSTREAM_REPOSITORY}.git"
          upstream_dir=${INPUT_UPSTREAM_REPOSITORY##*/}
          target_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${TARGET_REPOSITORY}.git"
          git clone "${upstream_repo}" -b "${INPUT_UPSTREAM_BRANCH}" --single-branch
          cd "${upstream_dir}"
          git rm -r -f --cached .github
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "rm workflows"
          git push --force --follow-tags --tags "${target_repo}" "${INPUT_UPSTREAM_BRANCH}:${INPUT_TARGET_BRANCH}"
          rm -rf "../${upstream_dir}"                

  two:
    runs-on: ubuntu-latest 
    needs: one
    env:
      INPUT_GITHUB_TOKEN: ${{ secrets.PAT }}
      INPUT_UPSTREAM_REPOSITORY: ${{ secrets.UR2 }}
      TARGET_REPOSITORY: ${{ secrets.TR2 }}
      INPUT_TARGET_BRANCH: ${{ secrets.BR1 }}
      INPUT_UPSTREAM_BRANCH: ${{ secrets.BR1 }}
    steps:
      - name: Sync
        run: |
          upstream_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${INPUT_UPSTREAM_REPOSITORY}.git"
          upstream_dir=${INPUT_UPSTREAM_REPOSITORY##*/}
          target_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${TARGET_REPOSITORY}.git"
          git clone "${upstream_repo}" -b "${INPUT_UPSTREAM_BRANCH}" --single-branch
          cd "${upstream_dir}"
          git push --force --follow-tags --tags "${target_repo}" "${INPUT_UPSTREAM_BRANCH}:${INPUT_TARGET_BRANCH}"
          rm -rf "../${upstream_dir}"    

  three:
    runs-on: ubuntu-latest
    needs: [one,two]
    env:
      INPUT_GITHUB_TOKEN: ${{ secrets.PAT }}
      INPUT_UPSTREAM_REPOSITORY: ${{ secrets.UR2 }}
      TARGET_REPOSITORY: ${{ secrets.TR2 }}
      INPUT_TARGET_BRANCH: ${{ secrets.BR2 }}
      INPUT_UPSTREAM_BRANCH: ${{ secrets.BR2 }}
    steps:
      - name: Sync
        run: |
          upstream_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${INPUT_UPSTREAM_REPOSITORY}.git"
          upstream_dir=${INPUT_UPSTREAM_REPOSITORY##*/}
          target_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${TARGET_REPOSITORY}.git"
          git clone "${upstream_repo}" -b "${INPUT_UPSTREAM_BRANCH}" --single-branch
          cd "${upstream_dir}"
          git push --force --follow-tags --tags "${target_repo}" "${INPUT_UPSTREAM_BRANCH}:${INPUT_TARGET_BRANCH}"
          rm -rf "../${upstream_dir}"  
